AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    # - 'spec/*.rb'
    - '**/generated_parser/*'

# Extra lines for readability
Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Configuration parameters: AllowForAlignment.
Layout/ExtraSpacing:
  Enabled: false

Layout/LineLength:
  Description: Limit lines to 80 characters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#80-character-limits
  Enabled: true
  Max: 130
  Exclude:
    - 'spec/ais_spec.rb'

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Enabled: false
  Max: 400

Metrics/AbcSize:
  Enabled: false
  Max: 50

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/MethodLength:
  Enabled: false
  Max: 50

# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 7

Style/BlockComments:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/Documentation:
  Enabled: true

Style/FormatString:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/WordArray:
  Exclude:
    - "spec/**/*.rb"

# if you find "a == 3" readable and "3 == a" 'unreadable', do not contribute to this project.
Style/YodaCondition:
  Enabled: false

# Offense count: 1
Metrics/CyclomaticComplexity:
  Enabled: false
  Max: 11

# Offense count: 1
Metrics/PerceivedComplexity:
  Enabled: false
  Max: 14

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

# Pretty sure I know what I'm doing here
Style/RescueStandardError:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
